language: csharp
mono:
  - 4.8.1.0
solution: GoogleMapsApi.sln
install:
  - nuget restore GoogleMapsApi.sln
  - nuget install NUnit.Runners -Version 3.2.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release GoogleMapsApi.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.2.0/tools/nunit3-console.exe ./GoogleMapsApi.Test/bin/Release/GoogleMapsApi.Test.dll
